language: c

compiler:
  - clang
  - gcc

install: 
  - sudo apt-get update || true
  - sudo apt-get install build-essential
  - sudo apt-get install libpcap-dev libtool autoconf automake autogen

before_script:
  - ./autogen.sh
  # init coverage to 0 (optional)
  - lcov --directory . --zerocounters

script:
  - ./configure
  - make

after_script:
  - cd tests
  - ./do.sh

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' 'packages/*' 'm4/*' 'doc/*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
